# This file is automatically generated from tests/test_async.py using `scripts/unasync.py`.
# Do not edit it by hand.
from __future__ import annotations

import textwrap

import pytest

from pynyaa import Category, Nyaa


def test_properties(nyaa_client: Nyaa) -> None:
    assert nyaa_client.base_url == "https://nyaa.si/"


@pytest.mark.vcr
def test_nyaa_default(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get("https://nyaa.si/view/1755409")
    assert nyaa.title == "[smol] Shelter (2016) (BD 1080p HEVC FLAC) | Porter Robinson & Madeon - Shelter"
    assert nyaa.submitter.name == "smol"
    assert nyaa.submitter.is_trusted is False
    assert nyaa.submitter.is_banned is False


@pytest.mark.vcr
def test_nyaa_trusted(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get("https://nyaa.si/view/1544043")
    assert nyaa.title == "[MTBB] I Want to Eat Your Pancreas (BD 1080p) | Kimi no Suizou wo Tabetai"
    assert nyaa.submitter.is_trusted is True
    assert nyaa.is_remake is False
    assert nyaa.is_trusted is True
    assert nyaa.category == Category.ANIME_ENGLISH_TRANSLATED


@pytest.mark.vcr
def test_nyaa_trusted_and_remake(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get("https://nyaa.si/view/1694824")
    assert (
        nyaa.title
        == "[MiniMTBB] Sound! Euphonium the Movie: Our Promise: A Brand New Day (BD 1080p) | Hibike! Euphonium: Chikai no Finale"
    )
    assert nyaa.is_remake is True
    assert nyaa.is_trusted is False
    assert nyaa.submitter.is_trusted is True


@pytest.mark.vcr
def test_nyaa_anon(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get(1765655)
    assert (
        nyaa.title
        == "[Kinoworm] Ascendance of a Bookworm P01v01-P05v08 + Fanbook v01-v03 + Royal Academy Stories First Year v01 + Short Story Collection v01 (J-Novel Club) (Premium)"
    )
    assert nyaa.url.__str__() == "https://nyaa.si/view/1765655"
    assert nyaa.information == "https://www.goodreads.com/series/220639-ascendance-of-a-bookworm-light-novel"
    assert nyaa.submitter.name == "Anonymous"
    assert nyaa.category == Category.LITERATURE_ENGLISH_TRANSLATED


@pytest.mark.vcr
def test_nyaa_banned(nyaa_client: Nyaa) -> None:
    # Thoughts and Prayers for our good friend succ_
    nyaa = nyaa_client.get("https://nyaa.si/view/1422797")
    assert nyaa.title == "[succ_] Tsugumomo [BDRip 1920x1080 x264 FLAC]"
    assert nyaa.submitter.is_trusted is False
    assert nyaa.submitter.is_banned is True
    assert len(nyaa.torrent.files) == 20


@pytest.mark.vcr
def test_nyaa_banned_and_trusted(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get("https://nyaa.si/view/884488")
    assert nyaa.title == "[FMA1394] Fullmetal Alchemist (2003) [Dual Audio] [US BD] (batch)"
    assert nyaa.submitter.is_trusted is True
    assert nyaa.submitter.is_banned is True
    assert len(nyaa.torrent.files) == 51


@pytest.mark.vcr
def test_nyaa_description(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get("https://nyaa.si/view/1992716")
    assert (
        nyaa.description
        == textwrap.dedent("""\
    [Steins;Gate 0](https://myanimelist.net/anime/30484/Steins_Gate_0)

    **Original subs**: WhyNot (23β), LostYears (01-23), GhostYears (24)  
    **TLC (dialogue)**: GeeYu (01-23)  
    **QC/editing**: motbob  
    **Additional QC**: arsenyshalin  

    You should probably watch "Episode 23β" (S00E01 in the Specials folder) before anything else. You should also read up on [Tanabata](https://en.wikipedia.org/wiki/Tanabata) if you're unfamiliar with its lore. Note that I omitted "probably" in that last sentence. Go do it.

    There are alternate honorifics tracks in this release. Set your media player to play "enm" language tracks by default to automatically play honorifics tracks.

    [Video quality comparisons](https://slow.pics/c/QtLFD8uA)  

    Please leave feedback in the comments, good or bad.  
    Please read this short [playback guide](https://gist.github.com/motbob/754c24d5cd381334bb64b93581781a81) if you want to know how to make the video and subtitles of this release look better.
    All components of this release are released into the public domain to the [greatest extent possible](https://gist.github.com/motbob/9a85edadca33c7b8a3bb4de23396d510).""")
    )


@pytest.mark.vcr
def test_nyaa_empty_info(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get("https://nyaa.si/view/5819")
    assert nyaa.information is None
    assert nyaa.description is not None


@pytest.mark.vcr
def test_nyaa_empty_desc(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get("https://nyaa.si/view/76777")
    assert nyaa.information is not None
    assert nyaa.description is None


@pytest.mark.vcr
def test_nyaa_empty_desc_info(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get("https://nyaa.si/view/1586776")
    assert nyaa.information is None
    assert nyaa.description is None


@pytest.mark.vcr
def test_search_single(nyaa_client: Nyaa) -> None:
    results = nyaa_client.search("smol shelter")
    for result in results:
        assert result.title == "[smol] Shelter (2016) (BD 1080p HEVC FLAC) | Porter Robinson & Madeon - Shelter"
        break


@pytest.mark.vcr
def test_nyaa_search_no_results(nyaa_client: Nyaa) -> None:
    results = nyaa_client.search("akldlaskdjsaljdksd")  # 0 results
    assert [i for i in results] == []
