# This file is automatically generated from tests/test_async.py using `scripts/unasync.py`.
# Do not edit it by hand.
from __future__ import annotations

import datetime as dt
import textwrap

import pytest

from pynyaa import Category, Nyaa


def test_properties(nyaa_client: Nyaa) -> None:
    assert nyaa_client.base_url == "https://nyaa.si/"


@pytest.mark.vcr
def test_nyaa_default(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get("https://nyaa.si/view/1755409")
    assert nyaa.id == 1755409
    assert nyaa.url == "https://nyaa.si/view/1755409"
    assert nyaa.title == "[smol] Shelter (2016) (BD 1080p HEVC FLAC) | Porter Robinson & Madeon - Shelter"
    assert nyaa.category is Category.ANIME_ENGLISH_TRANSLATED
    assert nyaa.submitter is not None
    assert nyaa.submitter.name == "smol"
    assert nyaa.submitter.is_trusted is False
    assert nyaa.submitter.is_banned is False
    assert nyaa.datetime == dt.datetime(2023, 12, 14, 9, 6, 18, tzinfo=dt.timezone.utc)
    assert nyaa.information == "https://anidb.net/anime/12482"
    assert nyaa.seeders == 15
    assert nyaa.leechers == 0
    assert nyaa.completed == 640
    assert nyaa.is_trusted is False
    assert nyaa.is_remake is False
    assert nyaa.description == (
        "Video: JPBD (Sony). Encoded by smolkitten.\n"
        "Audio: Japanese FLAC (2.0)\n"
        "Subtitles: Full subtitles [Harunatsu]\n"
        "[Mediainfo](https://pastebin.com/tLu6yxTZ) | [Comparisons](https://slow.pics/c/oPk6POK1) | [Discord](https://discord.gg/5QknG2PP6D)\n\n"
        "Harunatsu's subtitles were restyled."
    )
    assert nyaa.torrent == "https://nyaa.si/download/1755409.torrent"
    assert nyaa.magnet.startswith("magnet:?xt=urn:btih:ad596c24e64424aa6fe02c04c20eb25e57dbb042")


@pytest.mark.vcr
def test_nyaa_trusted(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get("https://nyaa.si/view/1544043")
    assert nyaa.id == 1544043
    assert nyaa.url == "https://nyaa.si/view/1544043"
    assert nyaa.title == "[MTBB] I Want to Eat Your Pancreas (BD 1080p) | Kimi no Suizou wo Tabetai"
    assert nyaa.category is Category.ANIME_ENGLISH_TRANSLATED
    assert nyaa.submitter is not None
    assert nyaa.submitter.name == "motbob"
    assert nyaa.submitter.is_trusted is True
    assert nyaa.submitter.is_banned is False
    assert nyaa.datetime == dt.datetime(2022, 6, 20, 0, 0, 18, tzinfo=dt.timezone.utc)
    assert nyaa.information == "#MTBB on Rizon"
    assert nyaa.seeders == 30
    assert nyaa.leechers == 0
    assert nyaa.completed == 3895
    assert nyaa.is_trusted is True
    assert nyaa.is_remake is False
    assert (
        nyaa.description
        == "[I Want to Eat Your Pancreas](https://myanimelist.net/anime/36098/Kimi_no_Suizou_wo_Tabetai)\n\nPAS subs, additional TS by [nedragrevev](https://github.com/nedragrevev/custom-subs).  \nNo 5.1 audio.\n\nThis BD had a lot of noise. I nuked the crap out of it. If you want a better encode with all the grain, grab a release that uses Beatrice-Raws (*not* D-Z0N3, that one is missing some scenes). For everyone else, this release looks much better than all the existing smaller and similar-sized encodes.\n\nThere is an alternate honorifics track in this release. Set your media player to play “enm” language tracks by default to automatically play honorifics tracks.\n\nPlease leave feedback in the comments, good or bad.  \nPlease read this short [playback guide](https://gist.github.com/motbob/754c24d5cd381334bb64b93581781a81) if you want to know how to make the video and subtitles of this release look better.\nAll components of this release are released into the public domain to the [greatest extent possible](https://gist.github.com/motbob/9a85edadca33c7b8a3bb4de23396d510)."
    )
    assert nyaa.torrent == "https://nyaa.si/download/1544043.torrent"
    assert nyaa.magnet.startswith("magnet:?xt=urn:btih:78e51b8285dd611dc1728d9b38dc1b8607cd0994")


@pytest.mark.vcr
def test_nyaa_trusted_and_remake(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get("https://nyaa.si/view/1694824")
    assert nyaa.id == 1694824
    assert nyaa.url == "https://nyaa.si/view/1694824"
    assert nyaa.title == (
        "[MiniMTBB] Sound! Euphonium the Movie: Our Promise: A Brand New Day (BD 1080p) "
        "| Hibike! Euphonium: Chikai no Finale"
    )
    assert nyaa.category is Category.ANIME_ENGLISH_TRANSLATED
    assert nyaa.submitter is not None
    assert nyaa.submitter.name == "motbob"
    assert nyaa.submitter.is_trusted is True
    assert nyaa.submitter.is_banned is False
    assert nyaa.datetime == dt.datetime(2023, 7, 19, 15, 18, 2, tzinfo=dt.timezone.utc)
    assert nyaa.information == "https://discord.gg/r9gyPwJeqW"
    assert nyaa.seeders == 10
    assert nyaa.leechers == 0
    assert nyaa.completed == 982
    assert nyaa.is_trusted is False
    assert nyaa.is_remake is True
    assert nyaa.description == (
        "This is a smaller and lower quality version of "
        "[Sound! Euphonium the Movie: Our Promise: A Brand New Day (BD 1080p)](https://nyaa.si/view/1694821).\n\n"
        "Since these videos are 10-bit AV1, you should make sure you have a fully updated version of your video player "
        "to avoid playback issues, whether it's [MPC](https://github.com/clsid2/mpc-hc/releases/tag/2.0.0), "
        "[mpv](https://mpv.io/), or [VLC](https://www.videolan.org/vlc/)."
    )
    assert nyaa.torrent == "https://nyaa.si/download/1694824.torrent"
    assert nyaa.magnet.startswith("magnet:?xt=urn:btih:19606f2e09b7013d9fcefbb67955766c19c32c5a")


@pytest.mark.vcr
def test_nyaa_anon(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get(1765655)

    assert nyaa.id == 1765655
    assert nyaa.url == "https://nyaa.si/view/1765655"
    assert nyaa.title == (
        "[Kinoworm] Ascendance of a Bookworm P01v01-P05v08 + Fanbook v01-v03 + "
        "Royal Academy Stories First Year v01 + Short Story Collection v01 (J-Novel Club) (Premium)"
    )
    assert nyaa.category is Category.LITERATURE_ENGLISH_TRANSLATED
    assert nyaa.submitter is None
    assert nyaa.datetime == dt.datetime(2024, 1, 13, 7, 20, 33, tzinfo=dt.timezone.utc)
    assert nyaa.information == "https://www.goodreads.com/series/220639-ascendance-of-a-bookworm-light-novel"
    assert nyaa.seeders == 6
    assert nyaa.leechers == 0
    assert nyaa.completed == 707
    assert nyaa.is_trusted is False
    assert nyaa.is_remake is False
    assert nyaa.description == (
        "### Join [![](https://discordapp.com/api/guilds/974468300304171038/widget.png?style=banner2)](https://discord.gg/snackbox) for bookworm cult\n"
        "---\n\n"
        "![](https://files.catbox.moe/7dr7oc.png)"
        "\n\nSorry about that, my house got raided because my drug dealer snitched on me."
        "\n\n---\n\n"
        "### Update\n- Added P5v08 Premium from AnimationBytings"
        "\n\n---\n\n"
        "### Bonus\nFinal volume of the Kinoworm saga\n\n![](https://files.catbox.moe/8bfabf.png)"
        "\n\n---\n\n"
        "### How to read this? \nGo here https://thewiki.moe/getting-started/literature"
    )
    assert nyaa.torrent == "https://nyaa.si/download/1765655.torrent"
    assert nyaa.magnet.startswith("magnet:?xt=urn:btih:8732a06d2087c71fddf5dc55d08512ebe146d445")


@pytest.mark.vcr
def test_nyaa_banned(nyaa_client: Nyaa) -> None:
    # Thoughts and Prayers for our good friend succ_
    nyaa = nyaa_client.get("https://nyaa.si/view/1422797")
    assert nyaa.title == "[succ_] Tsugumomo [BDRip 1920x1080 x264 FLAC]"
    assert nyaa.submitter is not None
    assert nyaa.submitter.is_trusted is False
    assert nyaa.submitter.is_banned is True


@pytest.mark.vcr
def test_nyaa_banned_and_trusted(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get("https://nyaa.si/view/884488")
    assert nyaa.title == "[FMA1394] Fullmetal Alchemist (2003) [Dual Audio] [US BD] (batch)"
    assert nyaa.submitter is not None
    assert nyaa.submitter.is_trusted is True
    assert nyaa.submitter.is_banned is True


@pytest.mark.vcr
def test_nyaa_description(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get("https://nyaa.si/view/1992716")
    assert (
        nyaa.description
        == textwrap.dedent("""\
    [Steins;Gate 0](https://myanimelist.net/anime/30484/Steins_Gate_0)

    **Original subs**: WhyNot (23β), LostYears (01-23), GhostYears (24)  
    **TLC (dialogue)**: GeeYu (01-23)  
    **QC/editing**: motbob  
    **Additional QC**: arsenyshalin  

    You should probably watch "Episode 23β" (S00E01 in the Specials folder) before anything else. You should also read up on [Tanabata](https://en.wikipedia.org/wiki/Tanabata) if you're unfamiliar with its lore. Note that I omitted "probably" in that last sentence. Go do it.

    There are alternate honorifics tracks in this release. Set your media player to play "enm" language tracks by default to automatically play honorifics tracks.

    [Video quality comparisons](https://slow.pics/c/QtLFD8uA)  

    Please leave feedback in the comments, good or bad.  
    Please read this short [playback guide](https://gist.github.com/motbob/754c24d5cd381334bb64b93581781a81) if you want to know how to make the video and subtitles of this release look better.
    All components of this release are released into the public domain to the [greatest extent possible](https://gist.github.com/motbob/9a85edadca33c7b8a3bb4de23396d510).""")
    )


@pytest.mark.vcr
def test_nyaa_empty_info(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get("https://nyaa.si/view/5819")
    assert nyaa.information is None
    assert nyaa.description is not None


@pytest.mark.vcr
def test_nyaa_empty_desc(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get("https://nyaa.si/view/76777")
    assert nyaa.information is not None
    assert nyaa.description is None


@pytest.mark.vcr
def test_nyaa_empty_desc_info(nyaa_client: Nyaa) -> None:
    nyaa = nyaa_client.get("https://nyaa.si/view/1586776")
    assert nyaa.information is None
    assert nyaa.description is None


@pytest.mark.vcr
def test_search_single(nyaa_client: Nyaa) -> None:
    results = nyaa_client.search("smol shelter")
    for result in results:
        assert result.title == "[smol] Shelter (2016) (BD 1080p HEVC FLAC) | Porter Robinson & Madeon - Shelter"
        break


@pytest.mark.vcr
def test_nyaa_search_no_results(nyaa_client: Nyaa) -> None:
    results = nyaa_client.search("akldlaskdjsaljdksd")  # 0 results
    assert [i for i in results] == []
