name: Tests

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/tests.yml'
      - 'src/**'
      - 'tests/**'
      - 'uv.lock'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/tests.yml'
      - 'src/**'
      - 'tests/**'
      - 'uv.lock'
  workflow_dispatch:
  workflow_call:


permissions:
  contents: read

env:
  FORCE_COLOR: 1
  UV_LOCKED: 1

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: false
          python-version: ${{ matrix.python-version }}

      - name: Run tests and generate coverage
        run: |
          uv sync --no-default-groups --group test
          uv run coverage run -m pytest -vv
          uv run coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          env_vars: OS,PYTHON
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
