name: Tests

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/test.yml'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --python ${{ matrix.python-version }}

      - name: Run tests and generate coverage
        run: |
          uv run coverage run -m pytest -vv
          uv run coverage xml

      - name: Build
        run: uv build

      - name: Get version
        id: version
        run: echo "version=$(uv run python -c 'import pynyaa; print(pynyaa.__version__)')" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: pynyaa-${{ steps.version.outputs.version }}-${{ matrix.python-version }}
          path: "dist/*"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          env_vars: OS,PYTHON
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
